trigger: none

pool:
  name: pool-D-EastUS2-01

steps:

- task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '0.13.4'

- task: TerraformTaskV1@0
  displayName: "Terraform INIT"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\terraform-template\wvd-deploy'
    backendServiceArm: 'sc-wvdpilot-azuredevops-core-P-01'
    backendAzureRmResourceGroupName: 'rg-DEVOPS-core-p-01'
    backendAzureRmStorageAccountName: 'stvmdevoptfstateastus201'
    backendAzureRmContainerName: 'wvdpocstate'
    backendAzureRmKey: 'wvdpocstate.tfstate'

- task: TerraformTaskV1@0
  displayName: "Terraform PLAN"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)\terraform-template\wvd-deploy'
    environmentServiceNameAzureRM: 'sc-wvdpilot-azuredevops-core-P-01'

- task: TerraformTaskV1@0
  displayName: "Terraform APPLY"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)\terraform-template\wvd-deploy'
    environmentServiceNameAzureRM: 'sc-wvdpilot-azuredevops-core-P-01'